# Site setings
name: 'Tiffany R. White Blog'
description: "Your friend Tiffany's tiny little weblog."
meta_description: "Your friend Tiffany's tiny little weblog."
logo: 'assets/images/logo-2.png'
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: https://tiffanywhite.dev
# disqus: 'justgoodthemes'
mailchimp_url: 'https://buttondown.email/api/emails/embed-subscribe/tiffanywhite'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: UA-61294063-1

# Author
author:
  name: 'Tiffany'
  image: 'authorimage-2.webp'
  greetings: 'Hi! 👋🏾'
  description: "My name is Tiffany. I'm a front-end developer for a large multinational consulting firm, writer and all around geek based in Swatara Township, PA."
  bio: 'Tiffany is a frontend developer, writer, and wannabe hacker.'

# Contact form setings
email: tiffany@tiffanywhite.dev
# contact_page_description: "Contact Me"
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'tiffanywhitedev'
# facebook: 'username'
github: 'twhite96'
# codepen: 'twhite96'
# dribbble: 'username'
# medium: '@username'
instagram: 'tiffanywhitedev'
# pinterest: 'tifftalkstech'
linkedin: 'tiffanyrwhite'
# producthunt: '@username'
# codesandbox: 'twhite96'
rss: '/feed.xml'

# Jekyll PWA
pwa:
  sw_src_filepath: sw.js # Optional
  sw_dest_filename: sw.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - "fonts/**/*"

# Webmentions
webmentions:
  username: tiffanywhite.dev
  cache_folder: .cache
  cache_bad_uris_for: 5
  legacy_domains:
    - https://tiffanywhite.tech
    - http://tiffanywhite.tech
    - https://helloburgh.me
    - https://helloburgh.me
    - https://twhite96.github.io
    - http://twhite96.github.io
  templates:
    count: _includes/webmentions/count.html
    likes: _includes/webmentions/likes.html
    replies: _includes/webmentions/replies.html
    reposts: _includes/webmentions/reposts.html
    webmentions: _includes/webmentions/webmentions.html

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Search
    url: /search/
  - text: Uses
    url: /uses/
  - text: Portfolio
    url: https://www.tiffanyrwhite.com
  - text: Resume
    url: https://resume.tiffanyrwhite.com
  - text: Privacy Policy
    url: /privacy-policy/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:year/:month/:day/:title/

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

# webp support
webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/images/"]

  # Whether to search in nested directories or not
  nested: true

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################
