# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Tiffany R. White Blog
tagline:          'Software dev, Pittsburgher, contrarian, and herder of cats.'
description:      'A Technical Blog by <a href="https://twitter.com/TiffanyW_412" target="_blank">Tiffany White</a>'
url:              'https://tiffanywhite.tech'
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Tiffany White'
  url:            https://twitter.com/TiffanyW_412

paginate:         5
paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
disqus:
  shortname: helloburgh

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.6.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/twhite96/TWBlog
