# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Tiffany R. White Blog
tagline:          'Software dev. Pittsburgher. Herder of cats and general contrarian.'
description:      'A Technical Blog by <a href="https://twitter.com/TiffanyW_412" target="_blank">Tiffany White</a>'
url:              'https://tiffanywhite.tech'
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

permalink: /:year/:month/:day/:title/

author:
  name:           'Tiffany White'
  url:            https://twitter.com/TiffanyW_412

paginate:         5
paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
disqus:
  shortname: helloburgh

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-cloudinary
  - jekyll-seo-tag

cloudinary:
  cloud_name: twhiteblog
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"

twitter:
  username: TiffanyW_412
  card: summary_large_image

# facebook:
#   app_id: 345024175945415
#   admins: 10213908832409124

logo: /assets/images/default_img.png
# Custom vars
version:            3.6.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/twhite96/
